# Generated by Django 5.1.1 on 2024-09-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Номер телефона')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('social_status', models.CharField(choices=[('Школьник(-ца)', 'Школьник(-ца)'), ('Студент', 'Студент'), ('Взрослый(-ая)', 'Взрослый(-ая)')], verbose_name='Социальный статус')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение:')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
