# Generated by Django 5.1.1 on 2024-09-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_high_schoolers_questions_questions_high_schooler_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='high_schooler_questions',
            new_name='high_schoolers_questions',
        ),
    ]
