# Generated by Django 5.1.1 on 2024-09-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_high_schooler_questions_questions_high_schoolers_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('questions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.questions')),
                ('high_schoolers_answers', models.CharField(max_length=150)),
                ('student_answers', models.CharField(max_length=150)),
                ('adults_answers', models.CharField(max_length=150)),
            ],
            bases=('questions.questions',),
        ),
    ]
