# Generated by Django 5.1.1 on 2024-09-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
